version: '3.8'
services:
  immich:
    image: ghcr.io/immich-app/immich-server:latest
    container_name: immich-server
    restart: unless-stopped
    ports:
      - "2283:2283"
    environment:
      - DATABASE_URL=postgresql://immich:immich@db:5432/immich
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  dummy-cors:
    build: .
    container_name: immich-cors-dummy
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
    ports:
      - "5000:5000"
  db:
    image: postgres:15
    container_name: immich-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_DB: immich
    volumes:
      - immich-db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: immich-redis
    restart: unless-stopped
volumes:
  immich-db-data:
